services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes: 
      - .:/django
  

  postgres:
    image: postgres:15.8-alpine3.20
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: root
      POSTGRES_DB: django
